from __future__ import annotations

import time
from abc import ABC, abstractmethod

from typing import Any, Dict, Optional




# 本地抽象接口：仅包含 UI 实际用到的方法
class TorqueBaseCard(ABC):
    @abstractmethod
    def connect(self) -> int: ...
    @abstractmethod
    def disconnect(self) -> int: ...
    @abstractmethod
    def set_servo(self, on: bool) -> int: ...
    @abstractmethod
    def set_profile(self, axis: int, vmin: float, vmax: float, acc: float, dec: float, stop: float = 0.0) -> int: ...
    @abstractmethod
    def set_band(self, axis: int, band_mm: float) -> int: ...
    @abstractmethod
    def move_abs(self, axis: int, pos: float) -> int: ...
    @abstractmethod
    def move_rel(self, axis: int, dist: float) -> int: ...
    @abstractmethod
    def stop(self, axis: int, mode: int = 0) -> int: ...
    @abstractmethod
    def is_done(self, axis: int) -> bool: ...
    @abstractmethod
    def get_position(self, axis: int) -> float: ...
    @abstractmethod
    def get_velocity(self, axis: int) -> float: ...
    @abstractmethod
    def home(self, axis: int) -> int: ...
    @abstractmethod
    def set_position(self, axis: int, pos: float = 0.0) -> int: ...
    @abstractmethod
    def read_status(self) -> Dict[str, Any]: ...
    @abstractmethod
    def push(self, force_n: float, dist_mm: float, vel_mm_s: float) -> int: ...
    @abstractmethod
    def precise_push(self, force_n: float, dist_mm: float, vel_mm_s: float, band_n: float, chk_ms: int) -> int: ...
    @abstractmethod
    def trigger_command(self, code: int) -> int: ...
    @abstractmethod
    def config_home(self, velocity: float, acceleration: float, deacceleration: float) -> int: ...
    # 可选扩展
    def get_version(self) -> Any: ...
    def is_moving(self) -> bool: return not self.is_done(0)
