from typing import Any, Dict, List, Tuple

class SensorBase:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.connected = False
        self.ser = None

    def connect(self) -> bool: ...
    def disconnect(self) -> bool: ...
    def configure(self) -> bool: ...
    def start_stream(self) -> bool: ...
    def stop_stream(self) -> bool: ...
    def zero_channels(self, channels: List[int] = None) -> bool: ...
    def read_data(self) -> List[Tuple[int, List[Tuple[float, ...]]]]: ...
    def get_sensor_info(self) -> Dict[str, Any]: ...